💄(template) override blogpost-badges
fccn/nau-richie-site-factory pull request #236
Opened 2024-05-10 17:22 UTC by sandroscosta

Override the `blogpost-badges.html` template to remove the unwanted `Richie news`, when sharing via Twitter

Ultimately we can remove the variables but I decided to keep them in, as it makes the code cleaner.

2024-05-13 09:01 UTC, igobranco requested changes
@sandroscosta 

We have also override the social share on course's pages ex: `templates/social-networks/course-badges.html` but using a different approach.
We only change the translation strings on the `force_translations.py`.
I think we should use a similar approach on both cases.

I searched using a regex on the file [src/richie/locale/pt_PT/LC_MESSAGES/django.po](https://github.com/openfun/richie/blob/master/src/richie/locale/pt_PT/LC_MESSAGES/django.po) and only view those 2 strings.

```
#: apps/core/templates/social-networks/blogpost-badges.html:3
#, python-format
msgid "Richie news: %(title)s"
msgstr "Notícias do Richie: %(title)s"

#: apps/core/templates/social-networks/blogpost-badges.html:4
#, python-format
msgid "Richie news: %(title)s %(url)s"
msgstr "Notícias de Richie: %(title)s %(url)s"
```

2024-05-14 13:57 UTC, igobranco requested changes
@sandroscosta you need to run again the `make i18n`.

Double check to remove the translations of the `templates/social-networks/blogpost-badges.html` template file.

Change the change log and commit messages to the different change implemented, no longer override the template but this commit is a force translation.

2024-05-15 08:59 UTC, igobranco commented
@sandroscosta  don't forget to fix the `CHANGELOG.md` conflicts.

2024-05-15 10:57 UTC, sandroscosta commented
> @sandroscosta don't forget to fix the `CHANGELOG.md` conflicts.

@igobranco Changed it to `Fixed` on the changelog. It should be all good now.

2024-05-16 09:03 UTC, merged